version: "3"

services:
  app:
    image: simplycodedsoftware/php:8.0
    volumes:
      - "$PWD:/data/app"
    user: 1000:1000
    container_name: "ecotone-quickstart"
    working_dir: "/data/app"
    command: sleep 999999
    networks:
      - default